### ISSUE TITLE
Text and style updates

### ISSUE THREAD

**Issue by ruf-io** [do-community/bandwidth-tool#2]
**Bandwidth Bars**
 - See what it looks like to put the allowance and consumption number and label on the bar itself.
![image](https://user-images.githubusercontent.com/11527560/74051027-307ab100-49a5-11ea-8e9a-a2efd1c79a78.png)

**Headers** 
 - H1: Bandwidth Planner
 - H2: Account Bandwidth Pool
 - H2: Droplets

**Updated Droplet View**
![image](https://user-images.githubusercontent.com/11527560/74049256-c01e6080-49a1-11ea-9e8b-62d947857e67.png)
- "Droplet will exist for" [INPUT] "(monthly)"
- "Outbound Data:" [INPUT] "(monthly)"
- Smaller, less red "Remove Droplet" button

**Add Pricing FAQ Section at end** - tbd on content

**Comment by MattIPv4** [comment]
Close in favor of #3 for FAQs
